version: "3.9"
services:
  web:
    # build: ./src/main/docker/Dockerfile.jvm
    image: quarkus/retail-pos-manager-jvm
    ports:
      - "8080:8080"
    environment:
      DB_URL: db:5432
      KAFKA_BOOTSTRAP_URL: kafka:9092
    depends_on:
      - db
      - kafka
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: retail3
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edgepos_manager
    ports:
      - "5432:5432"
  kafka:
    image: docker.io/bitnami/kafka:3.4
    #image: registry.access.redhat.com/amq7/amq-broker-rhel8
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
